### ISSUE TITLE
Password zichtbaar: src/WebApp-Database/app.js

### ISSUE THREAD

**Issue by tomptrs** [AP-Elektronica-ICT/ipd_2016-ipd16_groupburnout#1]
Heren,

je paswoorden worden hard-coded weergegeven! Opletten, zeker als je code op github platformen deelt! ( src/WebApp-Database/app.js )

var rival = new User({
        email:"s083731@ap.be",
        password:"abc123",
        first_name: "Rival",
        last_name: "Thompson",
        birthday: new Date(),
        gender:"m"
    });

**Comment by Rival-Thompson** [comment]
dit was een generiek voorbeeld voor een gebruiker. het wachtwoord was een fake wachtwoord dat niet gebruikt wordt in de db.
